# This is valid as long as the elixir image above is based on an erlang image that
# is built from Debian Buster
FROM debian:buster AS app

RUN apt-get update && \
    apt-get install -y openssl ca-certificates curl jq docker.io && \
    rm -rf /var/cache/apt /var/lib/apt

WORKDIR /app
ENV HOME=/app
ENV LANG=C.UTF-8
