on:
  - push


jobs:
  sanity-check:
    runs-on: ubuntu-20.04


    steps:
    - uses: actions/checkout@v3
    - uses: asdf-vm/actions/install@v1
    - name: check
      run:
        make setup synth
